name: Tacoma-Trivia-containers
services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    image: postgres:latest
    container_name: Tacoma-Trivia-DB
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: