name: stage-ci
on:
  push:
    branches: [stage]
  pull_request:
    branches: [stage]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '8.0.x'}
      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore -warnaserror
      - run: dotnet test ./TacomaTrivia.UnitTests/TacomaTrivia.UnitTests.csproj --no-build -v minimal 
  build-and-test:
    runs-on: [self-hosted,Windows, Stage]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: {dotnet-version: '8.0.x'}
      - name: Restore
        run: dotnet Restore
      - name: build
        run: dotnet build -c Release --no-restore
    